-- CreateTable
CREATE TABLE "Libro" (
    "ID_LIBRO" SERIAL NOT NULL,
    "ISBN" INTEGER NOT NULL,
    "TITULO" VARCHAR(255) NOT NULL,
    "AUTOR" VARCHAR(255) NOT NULL,
    "EDITORIAL" VARCHAR(255) NOT NULL,
    "FECHA_EDICION" VARCHAR(255) NOT NULL,
    "CALIFICACION" DECIMAL(18,2) NOT NULL,

    CONSTRAINT "Libro_pkey" PRIMARY KEY ("ID_LIBRO")
);

-- CreateTable
CREATE TABLE "Genero" (
    "ID_GENERO" SERIAL NOT NULL,
    "NOMBRE_GENERO" TEXT NOT NULL,

    CONSTRAINT "Genero_pkey" PRIMARY KEY ("ID_GENERO")
);

-- CreateTable
CREATE TABLE "Libro_Genero" (
    "ID_GENERO" INTEGER NOT NULL,
    "ID_LIBRO" INTEGER NOT NULL,

    CONSTRAINT "Libro_Genero_pkey" PRIMARY KEY ("ID_GENERO","ID_LIBRO")
);

-- CreateTable
CREATE TABLE "Usuario" (
    "ID_USUARIO" SERIAL NOT NULL,
    "USUARIO" TEXT NOT NULL,
    "CONTRASENA" TEXT NOT NULL,
    "CORREO_ELECTRONICO" TEXT NOT NULL,
    "TIPO_USUARIO" TEXT NOT NULL,
    "FECHA_CREACION" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Usuario_pkey" PRIMARY KEY ("ID_USUARIO")
);

-- CreateTable
CREATE TABLE "Comentario" (
    "ID_COMENTARIO" SERIAL NOT NULL,
    "DESCRIPCION_COMENTARIO" TEXT NOT NULL,
    "FECHA_COMENTARIO" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ID_USUARIO" INTEGER NOT NULL,
    "ID_LIBRO" INTEGER NOT NULL,

    CONSTRAINT "Comentario_pkey" PRIMARY KEY ("ID_COMENTARIO")
);

-- CreateTable
CREATE TABLE "Ejemplar" (
    "NUM_EJEMPLAR" SERIAL NOT NULL,
    "FECHA_ADQUISICION" DATE NOT NULL,
    "UBICACION_LIBRERIA" VARCHAR(255) NOT NULL,
    "PRECIO" DECIMAL(10,2) NOT NULL,
    "ESTADO" VARCHAR(255) NOT NULL,
    "TIPO_TAPA" VARCHAR(255) NOT NULL,
    "ID_LIBRO" INTEGER NOT NULL,

    CONSTRAINT "Ejemplar_pkey" PRIMARY KEY ("NUM_EJEMPLAR")
);

-- CreateTable
CREATE TABLE "Ventas" (
    "ID_VENTAS" SERIAL NOT NULL,
    "CANTIDAD_LIBROS" INTEGER NOT NULL,
    "FECHA_HORA" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "IMPUESTOS" DECIMAL(10,2) NOT NULL,
    "SUBTOTAL" DECIMAL(10,2) NOT NULL,
    "TOTAL" DECIMAL(10,2) NOT NULL,
    "NUM_EJEMPLAR" INTEGER NOT NULL,
    "ID_USUARIO" INTEGER NOT NULL,

    CONSTRAINT "Ventas_pkey" PRIMARY KEY ("ID_VENTAS")
);

-- CreateIndex
CREATE UNIQUE INDEX "Libro_ISBN_key" ON "Libro"("ISBN");

-- CreateIndex
CREATE UNIQUE INDEX "Genero_NOMBRE_GENERO_key" ON "Genero"("NOMBRE_GENERO");

-- CreateIndex
CREATE UNIQUE INDEX "Usuario_USUARIO_key" ON "Usuario"("USUARIO");

-- AddForeignKey
ALTER TABLE "Libro_Genero" ADD CONSTRAINT "Libro_Genero_ID_GENERO_fkey" FOREIGN KEY ("ID_GENERO") REFERENCES "Genero"("ID_GENERO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Libro_Genero" ADD CONSTRAINT "Libro_Genero_ID_LIBRO_fkey" FOREIGN KEY ("ID_LIBRO") REFERENCES "Libro"("ID_LIBRO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Comentario" ADD CONSTRAINT "Comentario_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "Usuario"("ID_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Comentario" ADD CONSTRAINT "Comentario_ID_LIBRO_fkey" FOREIGN KEY ("ID_LIBRO") REFERENCES "Libro"("ID_LIBRO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Ejemplar" ADD CONSTRAINT "Ejemplar_ID_LIBRO_fkey" FOREIGN KEY ("ID_LIBRO") REFERENCES "Libro"("ID_LIBRO") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Ventas" ADD CONSTRAINT "Ventas_NUM_EJEMPLAR_fkey" FOREIGN KEY ("NUM_EJEMPLAR") REFERENCES "Ejemplar"("NUM_EJEMPLAR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Ventas" ADD CONSTRAINT "Ventas_ID_USUARIO_fkey" FOREIGN KEY ("ID_USUARIO") REFERENCES "Usuario"("ID_USUARIO") ON DELETE RESTRICT ON UPDATE CASCADE;
